{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"gpuType":"T4","authorship_tag":"ABX9TyNQoF+4qgC+VS367wdxpokg"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU"},"cells":[{"cell_type":"code","execution_count":22,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"IJpczBhmapsZ","executionInfo":{"status":"ok","timestamp":1704215774631,"user_tz":-360,"elapsed":21947,"user":{"displayName":"A.M. Sajid Hasan","userId":"13704215136803552317"}},"outputId":"fca9b98d-552e-40f3-9553-0b1fe149f2aa"},"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (0.1.99)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0mRequirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.3.2)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0mRequirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)\n","Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)\n","Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0mRequirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (2.16.1)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.13.1)\n","Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.23.5)\n","Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (10.0.1)\n","Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)\n","Requirement already satisfied: dill<0.3.8,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.7)\n","Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (1.5.3)\n","Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.31.0)\n","Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.1)\n","Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.4.1)\n","Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.15)\n","Requirement already satisfied: fsspec<=2023.10.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2023.10.0,>=2023.1.0->datasets) (2023.6.0)\n","Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.9.1)\n","Requirement already satisfied: huggingface-hub>=0.19.4 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.19.4)\n","Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (23.2)\n","Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)\n","Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.1.0)\n","Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.4)\n","Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)\n","Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)\n","Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)\n","Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)\n","Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.4->datasets) (4.5.0)\n","Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.3.2)\n","Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.6)\n","Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2.0.7)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2023.11.17)\n","Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.3.post1)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0m"]}],"source":["!pip install sentencepiece\n","!pip install --upgrade pip\n","!pip install pandas\n","!pip install datasets"]},{"cell_type":"code","source":["import re\n","import os\n","import pandas as pd\n","from transformers import AutoTokenizer, AutoModelForSeq2SeqLM\n","from datasets import load_dataset\n","from google.colab import drive"],"metadata":{"id":"B0jZLtzsbYPd","executionInfo":{"status":"ok","timestamp":1704215774632,"user_tz":-360,"elapsed":17,"user":{"displayName":"A.M. Sajid Hasan","userId":"13704215136803552317"}}},"execution_count":23,"outputs":[]},{"cell_type":"code","source":["import torch\n","device = torch.device(\"cuda\")"],"metadata":{"id":"RFJnrHXBxkIw","executionInfo":{"status":"ok","timestamp":1704215774632,"user_tz":-360,"elapsed":15,"user":{"displayName":"A.M. Sajid Hasan","userId":"13704215136803552317"}}},"execution_count":24,"outputs":[]},{"cell_type":"code","source":["drive.mount('/content/drive')"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"rW-guUdzxSOe","executionInfo":{"status":"ok","timestamp":1704215777576,"user_tz":-360,"elapsed":2958,"user":{"displayName":"A.M. Sajid Hasan","userId":"13704215136803552317"}},"outputId":"d9e3b130-0a18-4de7-cb08-8849107c55f4"},"execution_count":25,"outputs":[{"output_type":"stream","name":"stdout","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"]}]},{"cell_type":"code","source":["# Function to handle whitespace in text\n","WHITESPACE_HANDLER = lambda k: re.sub('\\s+', ' ', re.sub('\\n+', ' ', k.strip()))\n","\n","# Load the csebuetnlp/xlsum dataset from Hugging Face\n","xlsum_dataset = load_dataset(\"csebuetnlp/xlsum\",\"bengali\", split=\"test\")\n","\n","# Assuming the 'article' is nested within a 'document' key\n","articles = xlsum_dataset['text']\n","\n","# Initialize the tokenizer and model\n","model_name = \"csebuetnlp/mT5_multilingual_XLSum\"\n","tokenizer = AutoTokenizer.from_pretrained(model_name)\n","model = AutoModelForSeq2SeqLM.from_pretrained(model_name)\n","model.to(device)\n","# Create a list to store the summaries\n","summaries = []\n","\n","for article_text in articles:\n","    article_text = WHITESPACE_HANDLER(article_text)\n","\n","   # Move input tensor to the same device as the model\n","    input_ids = tokenizer(\n","        [article_text],\n","        return_tensors=\"pt\",\n","        padding=\"max_length\",\n","        truncation=True,\n","        max_length=512\n","    )[\"input_ids\"].to(device)\n","\n","    output_ids = model.generate(\n","        input_ids=input_ids,\n","        min_length=70,\n","        max_length=90,\n","        no_repeat_ngram_size=2,\n","        num_beams=4\n","    )[0]\n","\n","    summary = tokenizer.decode(\n","        output_ids,\n","        skip_special_tokens=True,\n","        clean_up_tokenization_spaces=False\n","    )\n","\n","    summaries.append(summary)\n","\n","# Create a DataFrame with the summaries\n","result_df = pd.DataFrame({\"Article\": xlsum_dataset['text'], \"Summary\": summaries})\n","drive_path = '/content/drive/My Drive/Colab Notebooks/'\n","# Save the DataFrame to a CSV file\n","result_df.to_csv(os.path.join(drive_path, \"summaries.csv\"), index=False, encoding='utf-8')"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"boaG7h4Id5bs","executionInfo":{"status":"ok","timestamp":1704218122226,"user_tz":-360,"elapsed":2344657,"user":{"displayName":"A.M. Sajid Hasan","userId":"13704215136803552317"}},"outputId":"26ef18ec-5b70-4831-8ffe-bb0f363a1e14"},"execution_count":26,"outputs":[{"output_type":"stream","name":"stderr","text":["/usr/local/lib/python3.10/dist-packages/transformers/convert_slow_tokenizer.py:473: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.\n","  warnings.warn(\n"]}]},{"cell_type":"code","source":["result_df.to_csv(os.path.join(drive_path, \"summaries1.csv\"), index=False, encoding = 'utf-8-sig')\n"],"metadata":{"id":"_Ut1MNLfK2BG","executionInfo":{"status":"ok","timestamp":1704218122226,"user_tz":-360,"elapsed":13,"user":{"displayName":"A.M. Sajid Hasan","userId":"13704215136803552317"}}},"execution_count":27,"outputs":[]},{"cell_type":"code","source":["result_df.to_csv(os.path.join(drive_path, \"summaries2.csv\"), index=False, encoding = 'utf-16')\n"],"metadata":{"id":"8C43cfb9K_ir","executionInfo":{"status":"ok","timestamp":1704218122227,"user_tz":-360,"elapsed":11,"user":{"displayName":"A.M. Sajid Hasan","userId":"13704215136803552317"}}},"execution_count":28,"outputs":[]}]}